### ISSUE TITLE
Don't allow app to connect to internet at all

### ISSUE THREAD

**Issue by sts10** [sts10/medic#1]
Currently, for convenience, this tool allows users to check the passwords of a KeePass database against the HaveIBeenPwned [Pwned Passwords list](https://haveibeenpwned.com/Passwords). Users can perform this check in one of two ways: 

## 1. ONLINE HIBP Check

This tool takes the first 5 characters of the _hash_ of a password, and sends it to HaveIBeenPwned servers [via the service's API](https://haveibeenpwned.com/API/v2#PwnedPasswords). A number of potential matches come back, at which point the tool searches for an exact match (which would indicate an exposed password). As explained in [the API documentation](https://haveibeenpwned.com/API/v2#PwnedPasswords):

> When a password hash with the same first 5 characters is found in the Pwned Passwords repository, the API will respond with an HTTP 200 and include the suffix of every hash beginning with the specified prefix, followed by a count of how many times it appears in the data set. The API consumer can then search the results of the response for the presence of their source hash and if not found, the password does not exist in the data set.

Note: I currently force users to give explicit permission to perform this check:

```rustlang
println!("\n\nHeads up! I'll be sending the first 5 characters of the hashes of your passwords over the internet to HaveIBeenPwned. \nType allow to allow this");
if gets().unwrap() == "allow" {
    println!("Cool, I'll check your KeePass passwords over the internet now...\n");
    // ...
``` 

## 2. OFFLINE HIBP Check

The tool also allows users to perform this check entirely offline, however the user must first download the ~11GB exposed passwords list themselves, then provide that text file to this tool so it can do the check. To execute this procedure, this tool does not need to connect to the internet. 

For a variety of reasons, the OFFLINE method is more secure. Even though the ONLINE method only sends 5 characters of a hash of user passwords, that's still more than nothing. 

Thus I'm thinking of removing the ONLINE option (option 2). This way the entire tool never connects to the internet, which would be more in line with how [KeePassXC](https://keepassxc.org/), a commonly used application for interacting with KeePass databases, works by default (except features like "Download favicon").

I could even put a "paranoid" check in place such that tool can't open a KeePass database if it's able to connect to the internet, forcing the user to disable their internet connection in order to use the tool at all. 

## Questions 

What do you think? Should I offer the ONLINE check at all? Make it harder to access somehow? 

Are you less likely to use this tool because there's an _option_ to send 5 characters of your passwords' hashes over the internet? Does removing that feature in order to allay these security concerns provide a net benefit that outweighs the usefulness of the online check?

**Comment by codesections** [comment]
Hmm, one way to come at this could be to look at prior art—both in terms of getting a sense of best practices, but also in terms of seeing how you could add the most value.

Looking on crates.io, I see a couple of HIBP clients: [haveibeenpwned](https://crates.io/crates/haveibeenpwnd) and [checkpwn](https://crates.io/crates/checkpwn) plus the [pwned](https://crates.io/crates/pwned) library.  All three of those seem to be built around querying the API with hashes generated from the plaintext passwords.

That tells us two things at the same time: first, if you also went that way, you'd be in good company—those crates seem pretty popular and people haven't avoided them because of the online nature.

Second, however, since those crates already do it the online way, it seems like there could be some value in implementing the offline first approach—might give some more paranoid folks an option they wouldn't otherwise have.

But, in general, seems like either way would be fine.

**Comment by sts10** [comment]
Ah, I didn't see any of those three examples (I guess I only searched GitHub rather than crates.io?). Looking over the current options was/is a smart move; and it's definitely interesting that, at least from what I've gathered, the "offline" check isn't a common offering. 

Another, arguably more important, thing that separates my project is that it opens and loops through your KeePass database, as opposed to taking an individual, typed password. My thinking is that folks who (a) use KeePass and (b) are going to go to trouble of installing Rust to run and use a pretty ugly CLI are _probably_ a pretty security-conscious bunch and likely particularly wary of any of their sensitive info going over the 'net. 

All that said, I think I agree that either way is good. On one hand I like the idea of being able to say "This app works offline and in fact _only_ works offline," but also: maybe asking users to download an 11GB file is too big an ask...

**Comment by codesections** [comment]
> Another, arguably more important, thing that separates my project is that it opens and loops through your KeePass database, as opposed to taking an individual, typed password.

That's a good point.  It looks like they could probably take a list of passwords from a file too (or be trivially modified to do so) so someone could output their passwords to a file and then `shred` the file.  Of course, the truly paranoid probably wouldn't want to do that—but then those are exactly the sort of folks who *would* be willing to download an 11GB file.

Maybe you could make it less of an ask by having a convenience wrapper for torrenting it?  At least last time I checked, that was the preferred method of downloading the file, and I struggled to use that method (lacking experience with torrents/a client on my computer).

**Comment by sts10** [comment]
> It looks like they could probably take a list of passwords from a file too (or be trivially modified to do so) so someone could output their passwords to a file and then shred the file. 

KeePassXC does have an "Export to CSV option," but yeah, I don't _think_ generating (then shredding) extra files helps security? Unless I had one script that created a text file of your entries + hashes of the passwords, then a separate script that (a) compared those against the downloaded HIBP list and then (b) `shred`ed the text file. But script 1 would still have access to passwords in plaintext, and this would make it way harder to use. Separately, I can't think of any way in which generating files would help _usability_. 

> Maybe you could make it less of an ask by having a convenience wrapper for torrenting it?

Interesting idea! You mean have the script download the torrent for the user? Seems like a lot of work for us if we did it from scratch, but I see projects [like this](https://github.com/kenpratt/rusty_torrent) that I might be able to adapt to our needs. Either way, looks like it'd be a significant increase to the codebase, which usually I wouldn't mind, but given how sensitive this info is I'm not sure it'd be great to dump in more code I didn't write. 

Alternatively I could provide or link to some "How to download from a torrent" instructions in the README/docs? Personally I used [KTorrent](https://www.kde.org/applications/internet/ktorrent/) but I can also recommend [Transmission](https://transmissionbt.com/download/), which I've used with MacOS before. 

The bummer is that even if users are comfortable torrenting, they still need to wait for the large file to download.

**Comment by sts10** [comment]
FYI I added a rudimentary "paranoid mode", enabled via command line argument only. 

Honestly it might just be security theater... guess I should look for other examples of security-related software that enforce air-gapping of some level. Also, it complicated the code in a way that, I think, makes it harder to read/audit, so I'm not sure a net gain or loss for the overall security of the program...

**Comment by sts10** [comment]
Closing this issue for now, as the switch to a proper CLI mechanism for users (thanks to structopt) makes it more difficult to _accidentally_ send data over the internet.
